'use client'

import { useState, useRef, useEffect, useCallback } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Bot, Send, Mic, MicOff, Globe2, User, Zap, RefreshCw,
  Copy, ThumbsUp, ThumbsDown, Volume2, FileText, Camera, X,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { AIHologram } from '@/components/ai/ai-hologram'

type Role = 'user' | 'assistant'
type AgentMode = 'fan' | 'organizer' | 'security' | 'medical' | 'volunteer' | 'vendor'
type Language = 'en' | 'es' | 'fr' | 'ar' | 'pt' | 'de' | 'ja' | 'zh'

interface CollaborationStep {
  agent: AgentMode
  message: string
  status: string
}

interface Message {
  id: string
  role: Role
  content: string
  timestamp: Date
  tags?: string[]
  language?: Language
  collaboration?: CollaborationStep[]
}

const AGENT_MODES: { id: AgentMode; label: string; color: string; description: string }[] = [
  { id: 'fan',       label: 'Fan',       color: 'gold',    description: 'Navigate, find, explore' },
  { id: 'organizer', label: 'Organizer', color: 'emerald', description: 'Operations & reports' },
  { id: 'security',  label: 'Security',  color: 'blue',    description: 'Alerts & surveillance' },
  { id: 'medical',   label: 'Medical',   color: 'red',     description: 'Triage & response' },
  { id: 'volunteer', label: 'Volunteer', color: 'gold',    description: 'Tasks & coordination' },
  { id: 'vendor',    label: 'Vendor',    color: 'emerald', description: 'Inventory & sales' },
]

const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: 'en', label: 'English',  flag: '🇺🇸' },
  { code: 'es', label: 'Español',  flag: '🇪🇸' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'ar', label: 'العربية',  flag: '🇸🇦' },
  { code: 'pt', label: 'Português',flag: '🇧🇷' },
  { code: 'de', label: 'Deutsch',  flag: '🇩🇪' },
  { code: 'ja', label: '日本語',   flag: '🇯🇵' },
  { code: 'zh', label: '中文',     flag: '🇨🇳' },
]

const SUGGESTED_PROMPTS: Record<AgentMode, string[]> = {
  fan: [
    'Where is my seat 42B? (Seat navigation & Accessibility)',
    'Match information & schedules today',
    'Nearest food stall with shortest queue? (Food & Queue Prediction)',
    'Where is the World Cup merchandise stand?',
    'Translate match regulations into Spanish'
  ],
  organizer: [
    'Generate match day incident summary',
    'Calculate staffing recommendations for Sector 4',
    'Show crowd forecasting for Gate C entry surge',
    'Analyze vendor analytics & revenue breakdown',
    'Display overall Stadium KPIs overview'
  ],
  volunteer: [
    'Show SOP guidance for guest entry procedures',
    'Lost child response workflow protocol',
    'How do I request medical assistance for Section 104?',
    'Emergency routing path to nearest exit gate'
  ],
  security: [
    'Detect crowd anomalies in Sector 7 CCTV',
    'Handle suspicious activity alerts in West Stand',
    'Coordinate emergency security teams',
    'Show safe evacuation planning path maps'
  ],
  medical: [
    'Begin emergency medical triage checklist',
    'Locate nearest medical team & AED locations',
    'Ambulance routing lane status to Gate C',
    'Run heatstroke prediction analysis for today'
  ],
  vendor: [
    'Inventory prediction & levels for Food Zone F3',
    'Concession demand forecasting for second half',
    'Generate restocking suggestions for Sector B'
  ],
}

const AI_RESPONSES: Record<string, { text: string; tags: string[] }> = {
  default: {
    text: "I'm the StadiumVerse AI powered by **Gemini Pro** on Google Cloud. I have real-time access to all stadium systems, crowd flow data, venue maps, volunteer status, and operational intelligence. How can I assist you right now?",
    tags: ['Gemini Pro', 'Vertex AI', 'Real-time'],
  },
  'Where is my seat 42B?': {
    text: "**Seat 42B** is located in **Section 42, Row B, Seat 2** on Level 2 of MetLife Stadium. From your current location at Gate C: take Elevator E2 to Level 2, turn right, follow the blue seat markers for approximately 180 meters. Estimated walk time: **4 minutes**. Your seat is in the Premium West Stand with an excellent sideline view. Enjoy the match!",
    tags: ['Maps API', 'Navigation', 'Indoor'],
  },
  'Nearest food stall with shortest queue?': {
    text: "**Food Zone F3** on Level 2 near Section 104 is your best option right now — estimated wait time of only **2 minutes**. They offer hot dogs, nachos, soft drinks, and halal options. Second best: **Zone F8** near Gate D with 4 minutes wait. I can send turn-by-turn navigation to your device now.",
    tags: ['Real-time', 'Navigation', 'Queue AI'],
  },
  'Generate match day incident summary': {
    text: "**Match Day 14 Incident Summary — Generated by Gemini AI:**\n\n✅ **Medical:** 3 minor incidents (all treated on-site, 0 escalations)\n✅ **Security:** 1 anomaly alert (resolved in 6 min, false positive)\n⚠️ **Crowd:** Gate C surge at 76th min (redirected to Gate D successfully)\n✅ **Lost & Found:** 4 cases (all resolved within avg 5.2 min)\n✅ **Volunteers:** 480 active, 97/100 performance score\n\n**Overall Match Day Safety Score: 96.4/100** — Excellent.",
    tags: ['Generative AI', 'Gemini Pro', 'Report'],
  },
  'Anomaly alert in Sector 7': {
    text: "**SECURITY ALERT — Sector 7:** Camera feed shows unusual crowd concentration near Exit E7. Density is **91%**, exceeding the 85% threshold. **Recommended action:** Deploy Security Team Bravo (currently at nearby post B3). I've sent a push alert to Team Bravo and Supervisor Unit S-1. Real-time CCTV feed is now live on your security dashboard. Shall I initiate the crowd dispersal protocol?",
    tags: ['Security AI', 'Alert', 'CCTV', 'Critical'],
  },
  'Nearest AED locations': {
    text: "**3 AEDs within 150m of your position:**\n\n1. **AED-14** — 45m away, Gate C corridor, Level 1 (last checked: 2h ago, operational)\n2. **AED-09** — 78m away, Food Zone F3, Level 2 (operational)\n3. **AED-22** — 135m away, First Aid Station near Section 38 (with trained staff)\n\nA Medical Unit has been notified of your location. Response time: **estimated 90 seconds**. Do you need me to initiate emergency dispatch?",
    tags: ['Medical AI', 'Emergency', 'Navigation', 'Critical'],
  },
}

function TypingIndicator() {
  const [step, setStep] = useState(0)
  const steps = [
    { agent: 'Fan Agent', action: 'Calculating optimal seat pathways & accessibility check...', color: 'text-gold' },
    { agent: 'Security Agent', action: 'Analyzing sector crowd flows & gate sensor limits...', color: 'text-blue-400' },
    { agent: 'Medical Agent', action: 'Evaluating triage emergency path metrics...', color: 'text-rose-400' },
    { agent: 'Volunteer Agent', action: 'Consulting operational SOP guidelines & standby logs...', color: 'text-amber-400' }
  ]

  useEffect(() => {
    const interval = setInterval(() => {
      setStep(s => (s + 1) % steps.length)
    }, 1200)
    return () => clearInterval(interval)
  }, [])

  return (
    <div className="px-4 py-3 min-w-[280px]">
      <div className="flex items-center gap-2 mb-2">
        <div className="flex gap-1 items-center">
          {[0, 1, 2].map(i => (
            <motion.span
              key={i}
              className="w-1.5 h-1.5 rounded-full bg-gold"
              animate={{ y: [0, -4, 0] }}
              transition={{ duration: 0.6, repeat: Infinity, delay: i * 0.15 }}
              aria-hidden="true"
            />
          ))}
        </div>
        <span className="text-[10px] font-mono font-bold tracking-wider text-muted-foreground uppercase">
          Agent Collaboration Sync...
        </span>
      </div>
      
        <motion.div
          key={step}
          initial={{ opacity: 0, y: 5 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -5 }}
          transition={{ duration: 0.3 }}
          className="text-xs font-mono"
        >
          <span className={cn("font-bold", steps[step].color)}>{steps[step].agent}</span>: {steps[step].action}
        </motion.div>
      
    </div>
  )
}

function AgentSyncChain({ steps }: { steps: CollaborationStep[] }) {
  const getAgentLabel = (id: string) => {
    const found = AGENT_MODES.find(m => m.id === id)
    return found ? found.label + " Agent" : id.toUpperCase()
  }

  const getAgentColor = (id: string) => {
    if (id === 'fan') return 'text-gold border-gold/30 bg-gold/5'
    if (id === 'organizer') return 'text-emerald border-emerald/30 bg-emerald/5'
    if (id === 'security') return 'text-blue-400 border-blue-400/30 bg-blue-400/5'
    if (id === 'medical') return 'text-rose-400 border-rose-400/30 bg-rose-400/5'
    if (id === 'volunteer') return 'text-amber-400 border-amber-400/30 bg-amber-400/5'
    if (id === 'vendor') return 'text-cyan-400 border-cyan-400/30 bg-cyan-400/5'
    return 'text-muted-foreground border-border bg-muted/5'
  }

  return (
    <div className="mt-4 pt-3.5 border-t border-white/10 flex flex-col gap-2.5 w-full">
      <div className="flex items-center gap-1.5">
        <Bot className="w-3.5 h-3.5 text-gold animate-pulse" />
        <span className="text-[9px] font-mono font-black uppercase tracking-widest text-gold/80">
          StadiumVerse Agent Collaboration Flow
        </span>
      </div>
      <div className="flex flex-col gap-2 pl-1">
        {steps.map((step, idx) => (
          <motion.div
            key={idx}
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: idx * 0.12 }}
            className="flex items-start gap-2.5 text-xs font-mono"
          >
            <div className="relative flex flex-col items-center mt-1">
              <div className="h-2 w-2 rounded-full bg-emerald shadow-[0_0_8px_rgba(16,185,129,0.6)] animate-pulse" />
              {idx < steps.length - 1 && (
                <div className="w-[1px] h-6 bg-white/10 absolute top-2" />
              )}
            </div>

            <div className="flex-1">
              <span className={cn(
                "px-1.5 py-0.5 rounded text-[10px] font-bold border mr-2 uppercase",
                getAgentColor(step.agent)
              )}>
                {getAgentLabel(step.agent)}
              </span>
              <span className="text-muted-foreground text-[11px] leading-relaxed">
                {step.message}
              </span>
              <span className="ml-1.5 text-[9px] text-emerald bg-emerald/10 border border-emerald/20 px-1 rounded font-bold uppercase">
                {step.status}
              </span>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  )
}

function MessageBubble({ msg }: { msg: Message }) {
  const [copied, setCopied] = useState(false)
  const isUser = msg.role === 'user'

  const handleCopy = () => {
    navigator.clipboard.writeText(msg.content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const renderContent = (text: string) => {
    const lines = text.split('\n')
    return lines.map((line, li) => {
      const parts = line.split(/(\*\*[^*]+\*\*)/)
      return (
        <span key={li}>
          {parts.map((p, i) =>
            p.startsWith('**') && p.endsWith('**')
              ? <strong key={i} className="text-gold font-semibold">{p.slice(2, -2)}</strong>
              : <span key={i}>{p}</span>
          )}
          {li < lines.length - 1 && <br />}
        </span>
      )
    })
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className={cn('flex gap-3', isUser ? 'flex-row-reverse' : 'flex-row')}
    >
      {/* Avatar */}
      <div className={cn(
        'w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0 mt-1',
        isUser ? 'bg-muted' : 'gold-gradient'
      )}>
        {isUser
          ? <User className="w-3.5 h-3.5 text-muted-foreground" aria-hidden="true" />
          : <Zap className="w-3.5 h-3.5 text-black" aria-hidden="true" />
        }
      </div>

      <div className={cn('flex flex-col gap-1.5 max-w-lg', isUser ? 'items-end' : 'items-start')}>
        <div className={cn(
          'px-4 py-3 rounded-2xl text-sm leading-relaxed w-full',
          isUser
            ? 'bg-gold/20 border border-gold/30 text-foreground rounded-tr-sm'
            : 'glass border border-glass-border text-foreground rounded-tl-sm'
        )}>
          {renderContent(msg.content)}
          {!isUser && msg.collaboration && msg.collaboration.length > 0 && (
            <AgentSyncChain steps={msg.collaboration} />
          )}
        </div>

        {/* Tags + actions */}
        {!isUser && (
          <div className="flex flex-wrap items-center gap-2">
            {msg.tags?.map(tag => (
              <span key={tag} className="text-xs px-2 py-0.5 rounded-full bg-emerald/10 text-emerald border border-emerald/20 font-mono">{tag}</span>
            ))}
            <div className="flex items-center gap-1 ml-1">
              <button onClick={handleCopy} className="p-1 rounded text-muted-foreground hover:text-foreground transition-colors" aria-label="Copy message">
                <Copy className="w-3 h-3" aria-hidden="true" />
              </button>
              <button className="p-1 rounded text-muted-foreground hover:text-emerald transition-colors" aria-label="Thumbs up">
                <ThumbsUp className="w-3 h-3" aria-hidden="true" />
              </button>
              <button className="p-1 rounded text-muted-foreground hover:text-destructive transition-colors" aria-label="Thumbs down">
                <ThumbsDown className="w-3 h-3" aria-hidden="true" />
              </button>
              <button className="p-1 rounded text-muted-foreground hover:text-gold transition-colors" aria-label="Read aloud">
                <Volume2 className="w-3 h-3" aria-hidden="true" />
              </button>
            </div>
          </div>
        )}

        <span className="text-xs text-muted-foreground/50">
          {msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
        </span>
      </div>
    </motion.div>
  )
}

export function AIAssistant() {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: '0',
      role: 'assistant',
      content: "Welcome to **StadiumVerse AI** — your intelligent stadium companion for FIFA World Cup 2026. I'm powered by **Gemini Pro** on Google Cloud with real-time access to all venue systems. Ask me anything about navigation, crowd flow, food, emergencies, or operations!",
      timestamp: new Date(),
      tags: ['Gemini Pro', 'Vertex AI', 'Live'],
    }
  ])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [agentMode, setAgentMode] = useState<AgentMode>('fan')
  const [language, setLanguage] = useState<Language>('en')
  const [isListening, setIsListening] = useState(false)
  const [showLangMenu, setShowLangMenu] = useState(false)
  const bottomRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLTextAreaElement>(null)

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, isLoading])

  const sendMessage = useCallback(async (text: string) => {
    if (!text.trim() || isLoading) return

    const userMsg: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: text.trim(),
      timestamp: new Date(),
      language,
    }
    setMessages(prev => [...prev, userMsg])
    setInput('')
    setIsLoading(true)

    let responseText = ""
    let responseTags: string[] = []
    let responseCollaboration: CollaborationStep[] = []

    try {
      const res = await fetch('/api/gemini', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: text.trim(), agentMode })
      })
      if (res.ok) {
        const data = await res.json()
        responseText = data.text
        responseTags = data.tags || []
        responseCollaboration = data.collaboration || []
      } else {
        throw new Error('API request failed')
      }
    } catch (err) {
      // Fallback if network/API is down
      const fallback = AI_RESPONSES[text.trim()] ?? {
        text: `I understand you're asking about "${text.trim()}". Based on real-time data from our **${agentMode.charAt(0).toUpperCase() + agentMode.slice(1)} AI** module: all systems are operating normally. I'm cross-referencing crowd flow data, venue maps, and operational status to provide you with the most accurate guidance. Could you provide more specific details so I can give you a more precise response?`,
        tags: [agentMode.charAt(0).toUpperCase() + agentMode.slice(1) + ' AI', 'Gemini Pro', 'Real-time'],
      }
      responseText = fallback.text
      responseTags = fallback.tags
      responseCollaboration = [
        { agent: agentMode, message: 'Initiated local offline fallback processor', status: 'completed' }
      ]
    }

    const aiMsg: Message = {
      id: (Date.now() + 1).toString(),
      role: 'assistant',
      content: responseText,
      timestamp: new Date(),
      tags: responseTags,
      collaboration: responseCollaboration,
    }
    setMessages(prev => [...prev, aiMsg])
    setIsLoading(false)
  }, [isLoading, agentMode, language])

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    sendMessage(input)
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
      e.preventDefault()
      sendMessage(input)
    }
  }

  const colorMap: Record<string, string> = {
    gold:    'bg-gold/10 border-gold/30 text-gold hover:bg-gold/20',
    emerald: 'bg-emerald/10 border-emerald/30 text-emerald hover:bg-emerald/20',
    blue:    'bg-blue-accent/10 border-blue-accent/30 text-blue-accent hover:bg-blue-accent/20',
    red:     'bg-destructive/10 border-destructive/30 text-destructive hover:bg-destructive/20',
  }

  const currentModeLabel = AGENT_MODES.find(m => m.id === agentMode)?.label || 'Core System'

  return (
    <div className="h-[calc(100vh-64px)] flex flex-col lg:flex-row max-w-screen-xl mx-auto">
      {/* Sidebar */}
      <aside className="hidden lg:flex flex-col w-72 border-r border-border/30 p-4 gap-4 overflow-y-auto" aria-label="AI Assistant settings">
        {/* Hologram Display */}
        <AIHologram 
          status={isListening ? 'listening' : isLoading ? 'thinking' : 'idle'} 
          modeName={currentModeLabel}
        />

        {/* Mode selector */}
        <div>
          <p className="text-xs font-mono text-muted-foreground/60 uppercase tracking-widest mb-3">AI Mode</p>
          <div className="grid grid-cols-2 gap-2">
            {AGENT_MODES.map(({ id, label, color, description }) => (
              <button
                key={id}
                onClick={() => setAgentMode(id)}
                className={cn(
                  'p-2.5 rounded-xl border text-left transition-all',
                  agentMode === id
                    ? colorMap[color]
                    : 'border-border/30 text-muted-foreground hover:border-border hover:text-foreground glass'
                )}
                aria-pressed={agentMode === id}
              >
                <div className="text-xs font-semibold">{label}</div>
                <div className="text-xs opacity-60 mt-0.5">{description}</div>
              </button>
            ))}
          </div>
        </div>

        {/* Suggested prompts */}
        <div>
          <p className="text-xs font-mono text-muted-foreground/60 uppercase tracking-widest mb-3">Suggested</p>
          <div className="flex flex-col gap-1.5">
            {SUGGESTED_PROMPTS[agentMode].map(p => (
              <button
                key={p}
                onClick={() => sendMessage(p)}
                className="text-left text-xs text-muted-foreground hover:text-foreground px-3 py-2 rounded-lg hover:bg-muted/30 transition-colors border border-transparent hover:border-border/30"
              >
                {p}
              </button>
            ))}
          </div>
        </div>

        {/* Stats */}
        <div className="mt-auto glass glow-border-gold rounded-xl p-3">
          <p className="text-xs font-mono text-gold mb-2">Session Stats</p>
          <div className="flex flex-col gap-1.5 text-xs">
            <div className="flex justify-between">
              <span className="text-muted-foreground">Messages</span>
              <span className="text-foreground font-mono">{messages.length}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Model</span>
              <span className="text-gold font-mono">Gemini Pro</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Language</span>
              <span className="text-foreground font-mono">{language.toUpperCase()}</span>
            </div>
          </div>
        </div>
      </aside>

      {/* Chat area */}
      <div className="flex-1 flex flex-col min-w-0">
        {/* Chat header */}
        <div className="flex items-center gap-3 px-5 py-3 border-b border-border/30 glass">
          <div className="w-9 h-9 rounded-xl gold-gradient flex items-center justify-center">
            <Bot className="w-5 h-5 text-black" aria-hidden="true" />
          </div>
          <div>
            <div className="font-semibold text-sm">Gemini Stadium AI</div>
            <div className="flex items-center gap-1.5 text-xs text-emerald">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald animate-pulse" aria-hidden="true" />
              Online · {agentMode.charAt(0).toUpperCase() + agentMode.slice(1)} Mode
            </div>
          </div>
          <div className="ml-auto flex items-center gap-2">
            {/* Language selector */}
            <div className="relative">
              <button
                onClick={() => setShowLangMenu(p => !p)}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl glass border border-border/30 text-xs text-muted-foreground hover:text-foreground transition-colors"
                aria-haspopup="listbox"
                aria-expanded={showLangMenu}
                aria-label="Select language"
              >
                <Globe2 className="w-3.5 h-3.5" aria-hidden="true" />
                {LANGUAGES.find(l => l.code === language)?.flag}
                {language.toUpperCase()}
              </button>
              
                {showLangMenu && (
                  <motion.div
                    initial={{ opacity: 0, y: -5 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -5 }}
                    className="absolute right-0 top-full mt-1 glass border border-border rounded-xl overflow-hidden z-50 w-40"
                    role="listbox"
                    aria-label="Language options"
                  >
                    {LANGUAGES.map(({ code, label, flag }) => (
                      <button
                        key={code}
                        onClick={() => { setLanguage(code); setShowLangMenu(false) }}
                        role="option"
                        aria-selected={language === code}
                        className={cn(
                          'w-full flex items-center gap-2 px-3 py-2 text-xs hover:bg-muted/30 transition-colors',
                          language === code ? 'text-gold bg-gold/10' : 'text-muted-foreground'
                        )}
                      >
                        {flag} {label}
                      </button>
                    ))}
                  </motion.div>
                )}
              
            </div>

            <button
              onClick={() => setMessages(msgs => [msgs[0]])}
              className="p-1.5 rounded-lg text-muted-foreground hover:text-foreground hover:bg-muted/30 transition-colors"
              aria-label="Clear chat"
            >
              <RefreshCw className="w-4 h-4" aria-hidden="true" />
            </button>
          </div>
        </div>

        {/* Messages */}
        <div
          className="flex-1 overflow-y-auto px-4 sm:px-6 py-6 flex flex-col gap-5"
          role="log"
          aria-label="Chat messages"
          aria-live="polite"
        >
          {messages.map(msg => (
            <MessageBubble key={msg.id} msg={msg} />
          ))}
          {isLoading && (
            <div className="flex gap-3 items-start">
              <div className="w-7 h-7 rounded-lg gold-gradient flex items-center justify-center mt-1">
                <Zap className="w-3.5 h-3.5 text-black" aria-hidden="true" />
              </div>
              <div className="glass rounded-2xl rounded-tl-sm border border-glass-border">
                <TypingIndicator />
              </div>
            </div>
          )}
          <div ref={bottomRef} />
        </div>

        {/* Mobile suggested prompts */}
        <div className="lg:hidden flex gap-2 px-4 overflow-x-auto pb-2 scrollbar-none">
          {SUGGESTED_PROMPTS[agentMode].slice(0, 2).map(p => (
            <button
              key={p}
              onClick={() => sendMessage(p)}
              className="flex-shrink-0 text-xs px-3 py-1.5 rounded-xl glass border border-border/30 text-muted-foreground hover:text-foreground transition-colors"
            >
              {p}
            </button>
          ))}
        </div>

        {/* Input */}
        <form onSubmit={handleSubmit} className="px-4 sm:px-6 pb-6 pt-3 border-t border-border/30">
          <div className="flex items-end gap-2 glass rounded-2xl border border-gold/20 px-4 py-3">
            <textarea
              ref={inputRef}
              value={input}
              onChange={e => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder={`Ask ${agentMode} AI anything...`}
              rows={1}
              className="flex-1 bg-transparent text-sm text-foreground placeholder:text-muted-foreground outline-none resize-none max-h-32"
              aria-label="Message input"
            />
            <div className="flex items-center gap-1.5 flex-shrink-0">
              <button
                type="button"
                onClick={() => setIsListening(p => !p)}
                className={cn(
                  'w-8 h-8 rounded-xl flex items-center justify-center transition-all',
                  isListening ? 'bg-destructive/20 text-destructive animate-pulse' : 'text-muted-foreground hover:text-foreground hover:bg-muted/30'
                )}
                aria-label={isListening ? 'Stop recording' : 'Start voice input'}
                aria-pressed={isListening}
              >
                {isListening ? <MicOff className="w-4 h-4" aria-hidden="true" /> : <Mic className="w-4 h-4" aria-hidden="true" />}
              </button>
              <button
                type="submit"
                disabled={!input.trim() || isLoading}
                className="w-8 h-8 rounded-xl gold-gradient flex items-center justify-center disabled:opacity-40 hover:scale-105 active:scale-95 transition-transform"
                aria-label="Send message"
              >
                <Send className="w-4 h-4 text-black" aria-hidden="true" />
              </button>
            </div>
          </div>
          <p className="text-xs text-muted-foreground/40 text-center mt-2">
            Powered by Gemini Pro · Vertex AI · Google Cloud · Press Enter to send
          </p>
        </form>
      </div>
    </div>
  )
}
